package com.mycompany.collegemanagement;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author Divyansh Prasad
 */
public class AdminPortal extends javax.swing.JFrame implements MouseListener {

    String USER_ID, PASSWORD, USER_TYPE;

    JLabel selectedItem;

    CardLayout rightPane;

    public AdminPortal(String USER_ID, String PASSWORD, String USER_TYPE) {
        this.USER_ID = USER_ID;
        this.PASSWORD = PASSWORD;
        this.USER_TYPE = USER_TYPE;

        initComponents();

        new CollegeDatabase();

//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
        scrlHeader.setText("     " + USER_TYPE);

        rightPane = (CardLayout) RightPanelMain.getLayout();
        rightPane.show(RightPanelMain, "DashBoardPaneStr");

        selectedItem = item1;

        
        item1.addMouseListener(this);
        item2.addMouseListener(this);
        item3.addMouseListener(this);
        item4.addMouseListener(this);
        item5.addMouseListener(this);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        ScrSideNavPane = new javax.swing.JScrollPane();
        SideNavPane = new javax.swing.JPanel();
        scrlHeader = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        RightPanelMain = new javax.swing.JPanel();
        ScrDashBoardPane = new javax.swing.JScrollPane();
        DashBoardPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ScrCoursesPane = new javax.swing.JScrollPane();
        CoursesPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ScrProgRepPane = new javax.swing.JScrollPane();
        CoursesPane1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ScrFacultiesPane = new javax.swing.JScrollPane();
        CoursesPane2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ScrTimeTablePane = new javax.swing.JScrollPane();
        CoursesPane3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 28, 48));

        jSplitPane1.setDividerSize(0);

        ScrSideNavPane.setBackground(new java.awt.Color(0, 28, 48));
        ScrSideNavPane.setBorder(null);
        ScrSideNavPane.setForeground(new java.awt.Color(255, 255, 255));
        ScrSideNavPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrSideNavPane.setToolTipText("");
        ScrSideNavPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrSideNavPane.setPreferredSize(new java.awt.Dimension(287, 780));

        SideNavPane.setBackground(new java.awt.Color(0, 28, 48));
        SideNavPane.setPreferredSize(new java.awt.Dimension(287, 780));

        scrlHeader.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        scrlHeader.setForeground(new java.awt.Color(255, 255, 255));
        scrlHeader.setText("     ADMIN");
        scrlHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(218, 255, 251)));
        scrlHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        item1.setBackground(new java.awt.Color(112, 255, 134));
        item1.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        item1.setForeground(new java.awt.Color(255, 255, 255));
        item1.setText("     DASHBOARD");
        item1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item1.setOpaque(true);

        item2.setBackground(new java.awt.Color(0, 28, 48));
        item2.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        item2.setForeground(new java.awt.Color(255, 255, 255));
        item2.setText("     AUTHENTICATION DATABASE");
        item2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item2.setOpaque(true);

        item3.setBackground(new java.awt.Color(0, 28, 48));
        item3.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        item3.setForeground(new java.awt.Color(255, 255, 255));
        item3.setText("     FACULTY DATABASE");
        item3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item3.setOpaque(true);

        item4.setBackground(new java.awt.Color(0, 28, 48));
        item4.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        item4.setForeground(new java.awt.Color(255, 255, 255));
        item4.setText("     STUDENTS DATABASE");
        item4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item4.setOpaque(true);

        item5.setBackground(new java.awt.Color(0, 28, 48));
        item5.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        item5.setForeground(new java.awt.Color(255, 255, 255));
        item5.setText("     MARKS DATABASE");
        item5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item5.setOpaque(true);

        javax.swing.GroupLayout SideNavPaneLayout = new javax.swing.GroupLayout(SideNavPane);
        SideNavPane.setLayout(SideNavPaneLayout);
        SideNavPaneLayout.setHorizontalGroup(
            SideNavPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(item1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(item2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
            .addComponent(item3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
            .addComponent(item4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
            .addComponent(item5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        SideNavPaneLayout.setVerticalGroup(
            SideNavPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideNavPaneLayout.createSequentialGroup()
                .addComponent(scrlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        ScrSideNavPane.setViewportView(SideNavPane);

        jSplitPane1.setLeftComponent(ScrSideNavPane);

        RightPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        RightPanelMain.setLayout(new java.awt.CardLayout());

        ScrDashBoardPane.setBorder(null);

        DashBoardPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Admin Dashboard");

        javax.swing.GroupLayout DashBoardPaneLayout = new javax.swing.GroupLayout(DashBoardPane);
        DashBoardPane.setLayout(DashBoardPaneLayout);
        DashBoardPaneLayout.setHorizontalGroup(
            DashBoardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(DashBoardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DashBoardPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DashBoardPaneLayout.setVerticalGroup(
            DashBoardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(DashBoardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DashBoardPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ScrDashBoardPane.setViewportView(DashBoardPane);

        RightPanelMain.add(ScrDashBoardPane, "DashBoardStr");

        ScrCoursesPane.setBorder(null);

        CoursesPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Courses");

        javax.swing.GroupLayout CoursesPaneLayout = new javax.swing.GroupLayout(CoursesPane);
        CoursesPane.setLayout(CoursesPaneLayout);
        CoursesPaneLayout.setHorizontalGroup(
            CoursesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(CoursesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CoursesPaneLayout.setVerticalGroup(
            CoursesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(CoursesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ScrCoursesPane.setViewportView(CoursesPane);

        RightPanelMain.add(ScrCoursesPane, "CoursesStr");

        ScrProgRepPane.setBorder(null);

        CoursesPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("PROGRESS REP");

        javax.swing.GroupLayout CoursesPane1Layout = new javax.swing.GroupLayout(CoursesPane1);
        CoursesPane1.setLayout(CoursesPane1Layout);
        CoursesPane1Layout.setHorizontalGroup(
            CoursesPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(CoursesPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CoursesPane1Layout.setVerticalGroup(
            CoursesPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(CoursesPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ScrProgRepPane.setViewportView(CoursesPane1);

        RightPanelMain.add(ScrProgRepPane, "ProgRepStr");

        ScrFacultiesPane.setBorder(null);

        CoursesPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("FACULTIES");

        javax.swing.GroupLayout CoursesPane2Layout = new javax.swing.GroupLayout(CoursesPane2);
        CoursesPane2.setLayout(CoursesPane2Layout);
        CoursesPane2Layout.setHorizontalGroup(
            CoursesPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(CoursesPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPane2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CoursesPane2Layout.setVerticalGroup(
            CoursesPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(CoursesPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPane2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ScrFacultiesPane.setViewportView(CoursesPane2);

        RightPanelMain.add(ScrFacultiesPane, "FacultiesStr");

        ScrTimeTablePane.setBorder(null);

        CoursesPane3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("TIME TABLE");

        javax.swing.GroupLayout CoursesPane3Layout = new javax.swing.GroupLayout(CoursesPane3);
        CoursesPane3.setLayout(CoursesPane3Layout);
        CoursesPane3Layout.setHorizontalGroup(
            CoursesPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(CoursesPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CoursesPane3Layout.setVerticalGroup(
            CoursesPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(CoursesPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CoursesPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ScrTimeTablePane.setViewportView(CoursesPane3);

        RightPanelMain.add(ScrTimeTablePane, "TimeTableStr");

        jSplitPane1.setRightComponent(RightPanelMain);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoursesPane;
    private javax.swing.JPanel CoursesPane1;
    private javax.swing.JPanel CoursesPane2;
    private javax.swing.JPanel CoursesPane3;
    private javax.swing.JPanel DashBoardPane;
    private javax.swing.JPanel RightPanelMain;
    private javax.swing.JScrollPane ScrCoursesPane;
    private javax.swing.JScrollPane ScrDashBoardPane;
    private javax.swing.JScrollPane ScrFacultiesPane;
    private javax.swing.JScrollPane ScrProgRepPane;
    private javax.swing.JScrollPane ScrSideNavPane;
    private javax.swing.JScrollPane ScrTimeTablePane;
    private javax.swing.JPanel SideNavPane;
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel item4;
    private javax.swing.JLabel item5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel scrlHeader;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {

        selectedItem.setBackground(new Color(0x001C30));
        selectedItem = (JLabel) e.getSource();

        if (e.getSource() == item1) {
            item1.setBackground(new Color(0x70FF86));
            rightPane.show(RightPanelMain, "DashBoardStr");
        } else if (e.getSource() == item2) {
            item2.setBackground(new Color(0x70FF86));
            rightPane.show(RightPanelMain, "CoursesStr");
        } else if (e.getSource() == item3) {
            item3.setBackground(new Color(0x70FF86));
            rightPane.show(RightPanelMain, "ProgRepStr");
        } else if (e.getSource() == item4) {
            item4.setBackground(new Color(0x70FF86));
            rightPane.show(RightPanelMain, "FacultiesStr");
        } else if (e.getSource() == item5) {
            item5.setBackground(new Color(0x70FF86));
            rightPane.show(RightPanelMain, "TimeTableStr");
        }

    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {
        if (e.getSource() == item1) {
            item1.setBackground(new Color(0x70FF86));
        } else if (e.getSource() == item2) {
            item2.setBackground(new Color(0x70FF86));
        } else if (e.getSource() == item3) {
            item3.setBackground(new Color(0x70FF86));
        } else if (e.getSource() == item4) {
            item4.setBackground(new Color(0x70FF86));
        } else if (e.getSource() == item5) {
            item5.setBackground(new Color(0x70FF86));
        }

    }

    @Override
    public void mouseExited(MouseEvent e) {
        if (e.getSource() == item1 && e.getSource() != selectedItem) {
            item1.setBackground(new Color(0x001C30));
        } else if (e.getSource() == item2 && e.getSource() != selectedItem) {
            item2.setBackground(new Color(0x001C30));
        } else if (e.getSource() == item3 && e.getSource() != selectedItem) {
            item3.setBackground(new Color(0x001C30));
        } else if (e.getSource() == item4 && e.getSource() != selectedItem) {
            item4.setBackground(new Color(0x001C30));
        } else if (e.getSource() == item5 && e.getSource() != selectedItem) {
            item5.setBackground(new Color(0x001C30));
        }
    }
}
